# Тема “Вычисления с помощью Numpy”

In [66]:
import numpy as np

#### Задание 1

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [126]:
a = np.array([[1,6], [2,8], [3,11], [3,10], [1,7]])

In [127]:
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [88]:
mean_a = a.mean(axis=0)

In [93]:
print(mean_a)

[2.  8.4]


#### Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [95]:
a_centered = a - np.array([mean_a for i in range (5)])
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [100]:
a_centered = a - mean_a 
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


#### Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [99]:
a_centered_sp=a_centered[:,0]@a_centered[:,1]
print(a_centered_sp)

8.0


In [105]:
print(a_centered_sp / (a.shape[0]-1))


2.0


#### Задание 4 **

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [130]:
a1 = a.transpose()
print(a1)
print()
print(a1.ndim)

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]

2


In [132]:
np.cov(a1)[0,1]

2.0

# Тема “Работа с данными в Pandas”

In [99]:
import pandas as pd

Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники']


In [100]:
authors1 = {"author_id": [1, 2, 3], "author_name": ['Тургенев', 'Чехов', 'Островский']}
print(authors1)
print()
authors = pd.DataFrame(authors1)
authors

{'author_id': [1, 2, 3], 'author_name': ['Тургенев', 'Чехов', 'Островский']}



author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [101]:
books = pd.DataFrame({"author_id":[1, 1, 1, 2, 2, 3, 3],
                      "book_title":['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 
                      "price":[35,15,18,24,29,10,9]})
books

author_id            book_title  price
0          1           Отцы и дети     35
1          1                 Рудин     15
2          1     Дворянское гнездо     18
3          2      Толстый и тонкий     24
4          2       Дама с собачкой     29
5          3                 Гроза     10
6          3  Таланты и поклонники      9

#### Задание 2

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.


In [112]:
authors_price = pd.merge(authors, books, on='author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети     35
1          1    Тургенев                 Рудин     15
2          1    Тургенев     Дворянское гнездо     18
3          2       Чехов      Толстый и тонкий     24
4          2       Чехов       Дама с собачкой     29
5          3  Островский                 Гроза     10
6          3  Островский  Таланты и поклонники      9

#### Задание 3

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.


In [103]:
top5 = (authors_price.sort_values(by='price', ascending=False)).head(5)
top5

author_id author_name         book_title  price
0          1    Тургенев        Отцы и дети     35
4          2       Чехов    Дама с собачкой     29
3          2       Чехов   Толстый и тонкий     24
2          1    Тургенев  Дворянское гнездо     18
1          1    Тургенев              Рудин     15

#### Задание 4

Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.


In [109]:
authors_stat = authors_price.groupby(['author_name'])['price'].agg(['min', 'max', 'mean'])
authors_stat.rename(columns = {'min':'min_price', 'max':'max_price', 'mean':'mean_price'}, inplace = True )
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский           9         10    9.500000
Тургенев            15         35   22.666667
Чехов               24         29   26.500000

#### Задание 5**

Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.




In [113]:
authors_price.insert(4,"cover",['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'],False)
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети     35  твердая
1          1    Тургенев                 Рудин     15   мягкая
2          1    Тургенев     Дворянское гнездо     18   мягкая
3          2       Чехов      Толстый и тонкий     24  твердая
4          2       Чехов       Дама с собачкой     29  твердая
5          3  Островский                 Гроза     10   мягкая
6          3  Островский  Таланты и поклонники      9   мягкая

In [120]:
pd.pivot?


In [124]:
book_info = (pd.pivot_table(authors_price,index='author_name',columns='cover',values='price',aggfunc=np.sum)).fillna(0)
book_info

cover        мягкая  твердая
author_name                 
Островский     19.0      0.0
Тургенев       33.0     35.0
Чехов           0.0     53.0

In [126]:
book_info.to_pickle('book_info.pkl')

In [132]:
book_info2 = pd.read_pickle('book_info.pkl')

In [133]:
book_info2

cover        мягкая  твердая
author_name                 
Островский     19.0      0.0
Тургенев       33.0     35.0
Чехов           0.0     53.0